Allow standard mode to include open files at the top
darlal/obsidian-switcher-plus pull request #41
Opened 2022-04-20 06:30 UTC by reorx

[Quick Switcher++](https://github.com/darlal/obsidian-switcher-plus) is a very helpful tool, it allows me to search for open editors by typing a special prefix (`edt` by default) in the quick switcher. But I think it’s still not very intuitive, I want the “search any file and open it” action and “search for existing open file and activate it” to be combined into one thing to use.

In this PR I add a new setting item called “Include open files”. When it’s enabled, the switcher modal shows all the open files at the top with a different color style. If the open file is chosen, make that pane active; Other suggestions behave the same as the original, opening the file in the active pane.

https://i.imgur.com/bGLcQKl.mp4

The CSS color styles could be removed, it's included just for a demonstration purpose.

2022-04-22 02:33 UTC, darlal commented
Thanks for this PR. I will plan to take some time this weekend to do a review. Thanks.

2022-04-24 04:04 UTC, darlal requested changes
Thanks for this PR. I'm happy to work with you to get this PR to a state where it can be merged, for now, there are some issues that need addressing before it can be merged.

### Some general feedback

- This PR fails to build. `npm run build` reports dozens of errors. Things like missing semicolon, improper formatting, etc.. Further, general tidiness of the PR like removing console.log() statements, proper spacing should be addressed. The PR should build successfully at a minimum.

- Lack of test coverage. While bringing the entire codebase up to full coverage remains a work in progress, this PR significantly decreases coverage for some files which prior to this PR had high coverage. `npm run test` reports test coverage. Additionally, with this PR this [Settings test](https://github.com/darlal/obsidian-switcher-plus/blob/master/src/settings/__tests__/switcherPlusSettings.test.ts#L125) is now failing.

- Structural issues. A primary design goal of this project is to be a "drop in" replacement for the built-in system Switcher. A user should be able to simply "replace" the system switcher with switcher++ and have the default system functionality work as intended. There are some patterns that we use to maintain this constraint, and this PR goes against those patterns which result in some suboptimal control flow and duplication of code. I call attention to these in the inline comments. `Headings mdoe` although a misnomer, is the default "extended functionality" mode where cool features like this should go. In fact, headings mode does something like this already, and has a [natural hook](https://github.com/darlal/obsidian-switcher-plus/blob/master/src/Handlers/headingsHandler.ts#L127) already in place to take advantage of for building this feature. I highly recommend integrating this functionally there. I added more details around this in the inline comment.

Thanks for your work on this!

2022-04-26 02:18 UTC, reorx commented
Thanks for the careful and professional code review ☺️, I'll refine the code and give feedback this week when I got time.

2022-08-25 00:02 UTC, aidan-gibson commented
@reorx Any plans on working on this? I absolutely would love to have this feature, if I can help I'm more than happy to.

2022-08-30 03:05 UTC, darlal commented
Hey @aidan-gibson this feature is now live for headings mode with release [2.0.7](https://github.com/darlal/obsidian-switcher-plus/releases/tag/2.0.7). Thanks for the contribution @reorx! 😀

2022-08-30 03:05 UTC, closed without merging