feat: implement preserve last input
darlal/obsidian-switcher-plus pull request #95
Opened 2023-02-01 09:57 UTC by bytemain

Add the power to preserve user's last input value.
In some scene this make quick switcher more easier to use.

https://user-images.githubusercontent.com/13938334/216010658-c921b087-8408-4505-a501-c2d6b8ddd0d6.mp4

## Why Add Two Settings?

Because in Obisidian, Command Palette and Quick Switcher are different tools. The same as VSCode.
Using two settings make it configurable by difference people.

2023-02-06 00:52 UTC, darlal requested changes
Thanks for contributing this new feature! Please update the [documentation](https://github.com/darlal/obsidian-switcher-plus#general-settings) as well to reflect these new options. Thank you!

2023-02-06 00:52 UTC, darlal commented on src/switcherPlus/modeHandler.ts
>    insertSessionOpenModeCommandString(inputEl: HTMLInputElement): void {
It would be great to have this new logic covered by tests. Thanks!

2023-02-08 07:01 UTC, bytemain commented
it's diffcult to write the testcase, I'm still working on it.

2023-02-25 15:45 UTC, darlal commented
Hey @bytemain I'd love to get this merged and it's really close. Are you still working on it?

There's an existing [modeHandler test file](https://github.com/darlal/obsidian-switcher-plus/blob/master/src/switcherPlus/__tests__/modeHandler.test.ts) where new test cases can be added for [insertSessionOpenModeCommandString](https://github.com/darlal/obsidian-switcher-plus/blob/master/src/switcherPlus/__tests__/modeHandler.test.ts#L231). This also has an example for how to mock the HTMLInputElement that you can follow. I'm happy to help get this merged.

2023-02-26 08:34 UTC, bytemain commented
> Hey @bytemain I'd love to get this merged and it's really close. Are you still working on it?
> 
> 
> 
> There's an existing [modeHandler test file](https://github.com/darlal/obsidian-switcher-plus/blob/master/src/switcherPlus/__tests__/modeHandler.test.ts) where new test cases can be added for [insertSessionOpenModeCommandString](https://github.com/darlal/obsidian-switcher-plus/blob/master/src/switcherPlus/__tests__/modeHandler.test.ts#L231). This also has an example for how to mock the HTMLInputElement that you can follow. I'm happy to help get this merged.


I'm sorry I almost forgot about it. I will write a test now

2023-02-26 14:11 UTC, darlal commented
Awesome, thank you! Once that is done, we can go ahead and get this merged. Thanks!

2023-02-26 15:03 UTC, bytemain commented
@darlal Thanks for your guidance, I find it much easier to write test cases in `modeHandler`.

I have added some test scene. please have a look~ thanks!

2023-02-26 15:21 UTC, bytemain commented
<img width="733" alt="CleanShot 2023-02-26 at 23 21 16@2x" src="https://user-images.githubusercontent.com/13938334/221419755-b956c638-f8b0-455f-a2cf-ccb59966cd41.png">

`yarn ci` passed on my computer

2023-03-04 14:29 UTC, darlal approved these changes

2023-03-04 14:33 UTC, merged

2023-03-04 14:33 UTC, darlal commented
Thank you for this contribution @bytemain